# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField(max_length=100)),
                ('purchaser_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('purchase_count', models.IntegerField()),
                ('merchant_address', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(max_length=255)),
            ],
        ),
    ]
